# Créez un fichier Docker Compose chargé de déployer une plateforme collaborative
# d’hébergement de fichiers Nextcloud en respectant les contraintes suivantes :
#
# Le conteneur sera basé sur l’image officielle de Nextcloud, dans sa dernière version
# Le port par défaut de Nextcloud sera exposé afin d’être joignable à partir du port 8585 sur la machine hôte
# Un volume nommé "nextcloud" (managé par Docker) sera créé pour rendre persistant le dossier "/var/www/html" du conteneur

version: '3.8' # Version du fichier de configuration Docker Compose

services:
  nextcloud_db:
    image: mariadb # Utilisation de l'image officielle de MariaDB
    container_name: nextcloud_db # Nom du conteneur pour la base de données
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD  # Mot de passe de l'utilisateur root de mariadb
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données à créer à l'initialisation du conteneur
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données créée
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur créé

  nextcloud_app:
    image: nextcloud # Utilisation de l'image officielle de Nextcloud
    restart: always
    # Le port par défaut de Nextcloud sera exposé afin d’être joignable à partir du port 8585 sur la machine hôte
    ports:
      - "8585:80" # Exposition du port 80 du conteneur sur le port 8585 de la machine hôte
    # ports:
    #   - $NEXTCLOUD_PORT:80
    links:
      - nextcloud_db
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db  # Nom du conteneur de la base de données
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur de la base de données
