# Docker Compose chargé de déployer une plateforme collaborative
# Hébergement de fichiers Nextcloud respectant les contraintes suivantes :
# Le conteneur sera basé sur l’image de Nextcloud, dernière version
# Le port par défaut de Nextcloud sera exposé, joignable au port 8585 sur la machine hôte
# Un volume nommé "nextcloud" (managé par Docker) sera créé pour rendre persistant
# le dossier "/var/www/html" du conteneur

# EXECUTER LE DOCKER COMPOSE AVEC LA COMMANDE :
# docker compose -f 'docker_in_production\docker-compose.yml' up -d --build 'nextcloud_app'                                                                                                         

services:
  nextcloud_db:
    image: mariadb # Utilisation de l'image officielle de MariaDB
    container_name: nextcloud_db # Nom du conteneur pour la base de données
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW # Commande pour configurer MariaDB
    ports:
      - "3306:3306" # Exposition du port 3306 pour la base de données
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}  # Mot de passe root de mariadb
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}  # Nom de la bdd à créer à l'initialisation du conteneur
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}  # Nom de l'utilisateur de la bdd créée
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}  # Mot de passe utilisateur

  nextcloud_app:
    image: nextcloud # Utilisation de l'image officielle de Nextcloud
    restart: always
    # Le port par défaut de Nextcloud sera exposé afin d’être joignable à partir du port 8585 sur la machine hôte
    ports:
      - "${NEXTCLOUD_PORT}:80" # Exposition du port 80 du conteneur sur le port 8585 de la machine hôte
    links:
      - nextcloud_db # Lien vers le conteneur de la base de données
    volumes:
      - ./nextcloud:/var/www/html # Volume pour rendre persistant le dossier de Nextcloud
    environment:
      - MYSQL_HOST=nextcloud_db # Nom du conteneur de la base de données
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}  # Nom de la base de données
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}  # Nom de l'utilisateur de la base de données
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}  # Mot de passe utilisateur de la bdd
  
volumes:
  nextcloud: # Volume pour Nextcloud
    driver: local # Utilisation du driver local pour le volume
  db: # Volume pour la base de données
    driver: local # Utilisation du driver local pour le volume  